### ISSUE TITLE
Разобрать говнокод

### ISSUE THREAD

**Issue by SahDoum** [SahDoum/mathbot#1]
Везде где добавляются книги
Особенно catalog_manager.py

**Comment by gurland** [comment]
Almost everything is cleaned up for now.
Only catalog and book edit menu left for refactoring.

@SahDoum We could store `IUMCourse.timetable` and `IUMCourse.last_subscription` in appropriate `DateTimeField`, but unfortunately I couldn't find place in the old project where those fields were used.

Have you implemented logic related to courses' time fields? Well also I have to implement course input validation.

Also, take a look at my code in `dev-1` please.
